require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bancos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Banco. As you add validations to Banco, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Banco A", tipo: :postgres }
  }

  let(:invalid_attributes) {
    { name: "", tipo: nil }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Banco.create! valid_attributes
      get bancos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      banco = Banco.create! valid_attributes
      get banco_url(banco)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_banco_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      banco = Banco.create! valid_attributes
      get edit_banco_url(banco)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Banco" do
        expect {
          post bancos_url, params: { banco: valid_attributes }
        }.to change(Banco, :count).by(1)
      end

      it "redirects to the created banco" do
        post bancos_url, params: { banco: valid_attributes }
        expect(response).to redirect_to(banco_url(Banco.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Banco" do
        expect {
          post bancos_url, params: { banco: invalid_attributes }
        }.to change(Banco, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bancos_url, params: { banco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Banco B", tipo: :oracle }
      }

      it "updates the requested banco" do
        banco = Banco.create! valid_attributes
        patch banco_url(banco), params: { banco: new_attributes }
        banco.reload
        expect(banco.name).to eq("Banco B")
        expect(banco.tipo).to eq("oracle")
      end

      it "redirects to the banco" do
        banco = Banco.create! valid_attributes
        patch banco_url(banco), params: { banco: new_attributes }
        banco.reload
        expect(response).to redirect_to(banco_url(banco))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        banco = Banco.create! valid_attributes
        patch banco_url(banco), params: { banco: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested banco" do
      banco = Banco.create! valid_attributes
      expect {
        delete banco_url(banco)
      }.to change(Banco, :count).by(-1)
    end

    it "redirects to the bancos list" do
      banco = Banco.create! valid_attributes
      delete banco_url(banco)
      expect(response).to redirect_to(bancos_url)
    end
  end
end
